stages:
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/ -DskipTests=true"

cache:
  paths:
    - ${CI_PROJECT_DIR}/.m2/repository/

build:
  stage: build
  tags:
    - java21
    - maven
  script:
    - mvn clean install -f logging-starter/pom.xml
    - mvn clean package
  artifacts:
    paths: 
      - "**/target/*.jar"
    expire_in: 1 days

deploy-job:
  stage: deploy
  script:
    - scp **/target/*.jar ${DEV_USER}@${DEV_HOST}:${DEV_APP_PATH}/
    - ssh ${DEV_USER}@${DEV_HOST} "systemctl stop api.service && systemctl start api.service"
    - ssh ${DEV_USER}@${DEV_HOST} "systemctl stop gateway.service && systemctl start gateway.service"
    - ssh ${DEV_USER}@${DEV_HOST} "systemctl stop discovery.service && systemctl start discovery.service"
    - ssh ${DEV_USER}@${DEV_HOST} "systemctl stop replay.service && systemctl start replay.service"