stages:
  - build-logging-starter
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2"

cache:
#  key: $CI_COMMIT_SHA
  paths:
  - ${CI_PROJECT_DIR}/.m2

build-logging-starter:
  stage: build-logging-starter
  tags:
    - java21
    - maven
  script:
    - cd logging-starter
    - mvn clean package
  artifacts:
    paths: 
    - logging-starter/target/logging-starter-*.jar

build:
  stage: build
  tags:
    - java21
    - maven
  script:
    - ls -la logging-starter/target
    - mkdir -p ${CI_PROJECT_DIR}/.m2/repository/com/example/logging-starter/1.0.0/
    - cp ${CI_PROJECT_DIR}/logging-starter/target/logging-starter-*.jar ${CI_PROJECT_DIR}/.m2/repository/com/example/logging-starter/1.0.0/
    - mvn clean compile
