stages:
  - build-logging-starter
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2"

cache:
  key: $CI_JOB_NAME
  paths:
  - ${CI_PROJECT_DIR}/.m2

build-logging-starter:
  stage: build-logging-starter
  tags:
    - java21
    - maven
  script:
    - cd logging-starter
    - mvn clean package
  artifacts:
    paths: 
    - logging-starter/target/logging-starter-*.jar

build:
  stage: build
  tags:
    - java21
    - maven
  script:
    - mvn clean compile
