stages:
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2 -DskipTests=true"

cache:
#  key: $CI_COMMIT_SHA
  paths:
  - ${CI_PROJECT_DIR}/.m2

build:
  stage: build
  tags:
    - java21
    - maven
  script:
    - cd logging-starter
    - mvn clean package install
    - cd ../
    - mvn clean package
  artifacts:
    paths: 
    - "**/target/*.jar"

deploy-job:
  stage: deploy
  script:
    - scp **/target/*.jar ${DEV_USER}@${DEV_HOST}:${DEV_APP_PATH}/
