spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dota?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
logging:
  level:
    org.hibernate: TRACE